Ext.define('ClubManagement.model.Members', {
	extend: 'ClubManagement.model.Base',
	idProperty: 'memberId',
    fields: [
        {name: 'memberId', type: 'string'},
		{name: 'verein', type: 'string'},
		{name: 'nachname', type: 'string'},
		{name: 'vorname', type: 'string'},
		{name: 'anrede', type: 'string'},
		{name: 'title', type: 'string'},
		{name: 'zusatz', type: 'string'},
		{name: 'strasse', type: 'string'},
		{name: 'plz', type: 'string'},
		{name: 'ort', type: 'string'},
		{name: 'land', type: 'string'},
		{name: 'email', type: 'string'},
		{name: 'beruf', type: 'string'},
		{name: 'telefon1', type: 'string'},
		{name: 'telefon2', type: 'string'},
		{name: 'telefax', type: 'string'},
		{name: 'geschlecht', type: 'string'},
		{name: 'rekz', type: 'string'},
		{name: 'zahlungskz', type: 'string'},
		{name: 'blz', type: 'string'},
		{name: 'kontonummer', type: 'string'},
		{name: 'bank', type: 'string'},
		{name: 'BIC', type: 'string'},
		{name: 'IBAN', type: 'string'},
		{name: 'kontoinhaber', type: 'string'},
		{name: 'gebdat', type: 'date'},
		{name: 'eindat', type: 'date'},
		{name: 'sonderdat', type: 'date'},
		{name: 'ausdat', type: 'date'},
		{name: 'Mod_FN', type: 'string'},
		{name: 'Mod_USER', type: 'string'},
		{name: 'Mod_TIME', type: 'date'}
    ]
});
