services:
  nginx:
    image: nginx:1.27-alpine
    container_name: club_nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./nginx/club-management.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  php:
    build: .
    container_name: club_php
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./logs:/app/logs
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: club_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=club_management
      - MYSQL_USER=club
      - MYSQL_PASSWORD=club
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "club", "-pclub"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
